("main",0,[],[FUN False 0 5],[CASE 2 [CON 2 0,INT 1,VAR False 1],APP True [CON 2 0,INT 2,CON 0 1]])
("sum",1,[2],[ARG False 0,INT 0],[])
("sum#1",3,[],[ARG False 0,PRI 2 "(+)",VAR False 0],[CASE 2 [ARG False 1,INT 0]])
("sum#2",1,[],[INT 0],[])
("double",1,[],[ARG True 0,PRI 2 "(+)",ARG True 0],[])
("main",0,[],[FUN False 0 6],[APP False [VAR False (-2),INT 0]])
("main",0,[],[VAR True (-1),PRI 2 "(+)",VAR True (-1)],[])
