Red: Bytecode.hs CachingOctostack.hs Code.hs Collect.hs Encode.hs Heap.hs Hex.hs Main.hs Reduceron.hs RegFile.hs Syntax.hs Unistack.hs
	ghc $(J) --make -O2 -fspec-constr-count=4 -i../red-lava/modules/: Main.hs -o Red
